-- DDL Statements
CREATE TABLE TC_MASTER (
    TC_ID VARCHAR(50) PRIMARY KEY,
    TC_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    FLAG VARCHAR(20) NOT NULL,
    CREATED_BY VARCHAR(50),
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE DATETIME
);

CREATE TABLE PARAMETER_SCHEMA (
    SCHEMA_ID VARCHAR(100) PRIMARY KEY,
    SCHEMA_VERSION INT NOT NULL,
    SCHEMA_DEFINITION TEXT NOT NULL,
    IS_ACTIVE BIT DEFAULT 1,
    DESCRIPTION TEXT,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    MODIFIED_DATE DATETIME,
    UNIQUE (SCHEMA_ID, SCHEMA_VERSION)
);

CREATE TABLE STEP_CONFIG (
    STEP_NAME VARCHAR(100) PRIMARY KEY,
    DESCRIPTION TEXT,
    TIMEOUT_SECONDS INT NOT NULL DEFAULT 300,
    MAX_RETRIES INT NOT NULL DEFAULT 3,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    MODIFIED_DATE DATETIME
);

CREATE TABLE STEP_SCHEMA_MAPPING (
    STEP_NAME VARCHAR(100),
    SCHEMA_ID VARCHAR(100),
    IS_REQUIRED BIT DEFAULT 1,
    SEQUENCE_NO INT NOT NULL,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (STEP_NAME, SCHEMA_ID),
    FOREIGN KEY (STEP_NAME) REFERENCES STEP_CONFIG(STEP_NAME),
    FOREIGN KEY (SCHEMA_ID) REFERENCES PARAMETER_SCHEMA(SCHEMA_ID)
);

CREATE TABLE TC_STEPS (
    STEP_ID INT,
    TC_ID VARCHAR(50),
    STEP_NAME VARCHAR(100) NOT NULL,
    PARAMETERS TEXT,
    SEQUENCE_NO INT NOT NULL,
    STATUS VARCHAR(20),
    PRIMARY KEY (STEP_ID, TC_ID),
    FOREIGN KEY (TC_ID) REFERENCES TC_MASTER(TC_ID),
    FOREIGN KEY (STEP_NAME) REFERENCES STEP_CONFIG(STEP_NAME)
);

CREATE TABLE TC_EXECUTION_LOG (
    EXECUTION_ID BIGINT IDENTITY PRIMARY KEY,
    TC_ID VARCHAR(50),
    STEP_ID INT,
    START_TIME DATETIME,
    END_TIME DATETIME,
    STATUS VARCHAR(20),
    ERROR_MESSAGE TEXT,
    FOREIGN KEY (TC_ID) REFERENCES TC_MASTER(TC_ID)
);

-- Create indexes
CREATE INDEX idx_tc_master_flag ON TC_MASTER(FLAG);
CREATE INDEX idx_tc_steps_tcid ON TC_STEPS(TC_ID);
CREATE INDEX idx_execution_log_tcid ON TC_EXECUTION_LOG(TC_ID);
CREATE INDEX idx_parameter_schema_active ON PARAMETER_SCHEMA(IS_ACTIVE);
